name: Discord Embed Notify

on:
  push:
    branches:
      - main
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Verstuur naar Discord
        run: |
          # Pak de volledige commit message
          DESCRIPTION="${{ github.event.head_commit.message }}"

          # Stuur naar Discord
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"embeds\": [{
                   \"title\": \"\",
                   \"description\": \"$DESCRIPTION\",
                   \"color\": 16753920,
                   \"footer\": {
                     \"text\": \"Auteur: ${{ github.event.head_commit.author.name }}\",
                     \"icon_url\": \"https://github.com/${{ github.event.head_commit.author.username }}.png\"
                   }
                 }]
               }" \
               ${{ secrets.DISCORD_WEBHOOK }}
