name: Discord Embed Notify

on:
  push:
    branches:
      - main
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Verstuur meerdere commits in één embed naar Discord
        run: |
          # Initialiseer description
          DESCRIPTION=""

          # Loop door alle commits in deze push
          for COMMIT in $(jq -r '.commits[] | @base64' $GITHUB_EVENT_PATH); do
            _jq() {
              echo "${COMMIT}" | base64 --decode | jq -r "${1}"
            }
            COMMIT_MSG=$(_jq '.message')
            AUTHOR_NAME=$(_jq '.author.name')

            # Voeg commit toe aan de description
            DESCRIPTION+="$COMMIT_MSG\n$AUTHOR_NAME\n\n"
          done

          # Stuur één embed naar Discord
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"embeds\": [{
                   \"title\": \"Nieuwe commits in branch ${{ github.ref_name }}\",
                   \"description\": \"$DESCRIPTION\",
                   \"color\": 16753920,
                   \"footer\": {
                     \"text\": \"Noorddam Roleplay • GitHub\"
                   }
                 }]
               }" \
               ${{ secrets.DISCORD_WEBHOOK }}
