name: Discord Embed Notify

on:
  push:
    branches:
      - main
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Verstuur meerdere embeds in één bericht naar Discord
        run: |
          EMBEDS="["

          # Loop door alle commits
          for COMMIT in $(jq -c '.commits[]' $GITHUB_EVENT_PATH); do
            COMMIT_MSG=$(echo "$COMMIT" | jq -r '.message')
            AUTHOR_NAME=$(echo "$COMMIT" | jq -r '.author.name')
            AUTHOR_USERNAME=$(echo "$COMMIT" | jq -r '.author.username')

            EMBED="{
              \"title\": \"$COMMIT_MSG\",
              \"description\": \"Hier kan je extra info of uitleg zetten\",
              \"color\": 16753920,
              \"footer\": {
                \"text\": \"Auteur: $AUTHOR_NAME\",
                \"icon_url\": \"https://github.com/$AUTHOR_USERNAME.png\"
              }
            }"

            # Voeg komma toe tussen embeds als het niet de eerste is
            if [ "$EMBEDS" != "[" ]; then
              EMBEDS+=","
            fi
            EMBEDS+="$EMBED"
          done

          EMBEDS+="]"

          # Verstuur één POST met alle embeds
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"embeds\": $EMBEDS}" \
               ${{ secrets.DISCORD_WEBHOOK }}
