name: Discord Embed Notify

on:
  push:
    branches:
      - main
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Verstuur commits als één embed
        run: |
          DESCRIPTION=""
          COUNT=0
          MAX=10

          # Loop door alle commits in deze push
          for COMMIT in $(jq -c '.commits[]' $GITHUB_EVENT_PATH); do
            if [ $COUNT -ge $MAX ]; then
              break
            fi
            COMMIT_MSG=$(echo "$COMMIT" | jq -r '.message' | sed 's/"/\\"/g')
            AUTHOR_NAME=$(echo "$COMMIT" | jq -r '.author.name' | sed 's/"/\\"/g')
            DESCRIPTION+="$COMMIT_MSG — $AUTHOR_NAME\n\n"
            COUNT=$((COUNT+1))
          done

          TITLE="Nieuwe commits in branch ${{ github.ref_name }}"

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"embeds\": [{
                   \"title\": \"$TITLE\",
                   \"description\": \"$DESCRIPTION\",
                   \"color\": 16753920,
                   \"footer\": {
                     \"text\": \"Noorddam Roleplay • GitHub\"
                   }
                 }]
               }" \
               ${{ secrets.DISCORD_WEBHOOK }}
