name: Discord Updates

on:
  push:
    branches:
      - main  # Of welke branch je gebruikt

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        uses: Ilshidur/action-discord@v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            Nieuwe update in de repository!
            Auteur: ${{ github.actor }}
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
