- name: Verstuur meerdere embeds
  run: |
    EMBEDS=$(jq -n '[]')
    for COMMIT in $(jq -c '.commits[]' $GITHUB_EVENT_PATH); do
      TITLE=$(echo "$COMMIT" | jq -r '.message')
      AUTHOR_NAME=$(echo "$COMMIT" | jq -r '.author.name')
      AUTHOR_USERNAME=$(echo "$COMMIT" | jq -r '.author.username')

      EMBED=$(jq -n \
        --arg title "$TITLE" \
        --arg author_name "$AUTHOR_NAME" \
        --arg author_icon "https://github.com/$AUTHOR_USERNAME.png" \
        '{
          title: $title,
          color: 16753920,
          author: {
            name: $author_name,
            icon_url: $author_icon
          }
        }')

      EMBEDS=$(echo "$EMBEDS" | jq ". + [$EMBED]")
    done

    curl -H "Content-Type: application/json" \
         -X POST \
         -d "{\"embeds\": $EMBEDS}" \
         ${{ secrets.DISCORD_WEBHOOK }}
