name: Discord Embed Notify

on:
  push:
    branches:
      - main
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      # Checkout de repo zodat commits beschikbaar zijn
      - name: Checkout repository
        uses: actions/checkout@v4

      # Verstuur commits naar Discord met custom embed
      - name: Verstuur commits naar Discord
        uses: Sniddl/discord-commits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          template: "./discord-template.js"
          include-extras: false
